import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { FloatingNav } from "@/components/ui/floating-navbar";
import { navItems } from "@/data/main";
import { Roboto } from "next/font/google"

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['300','400', "500", '700'], 
  variable: '--font-roboto',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} antialiased`}
      >
        <FloatingNav navItems={navItems} />
        <div className="mt-[90px]">
          {children}
        </div>
      </body>
    </html>
  );
}
